version: "3"
services:
  web:
    container_name: ionic
    build: .
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 8100:3000
    privileged: true
    entrypoint:
      - sh
    command:
      - -c
      - |
        [ -f .exec-once ] || {
          npm install && touch .exec-once
        }
        npm run start